### ISSUE TITLE
Lazarus complains when finding PPUs with the same name

### ISSUE THREAD

**Issue by zeljkoavramovic** [Rest-Dataware/RDW-Componente#1]
With FUD (FpcUpDeluxe) generated 32bit Laz 2.0 fixes + FPC 3.2 fixes on Win10 x64, I've found that when Rest Dataware components are installed with OPM (Online Package Manager), Lazarus complains about finding PPUs with the same name in several directories and asks us if we want to ignore this situation and continue with compilation. Ignoring action helps and compilation is a success, but I believe that this should be fixed and users should not be bothered in such a way.

Rest Dataware has several packages, but each package outputs PPUs in different dir. Since packages use several same units, we end up with the same PPUs existing in several directories. That bothers Lazarus which reports that PPUs with same name are found at several places. I have attached modified LPK files for these packages changed in a way that they all output PPUs to the same lib dir, so each PPU exist only once. That way Lazarus will not ask us to ignore PPUs found in different places since they will be all in one place and no duplicates.

Attached is an archive with fixed LPK files.

Btw, thank you for sharing your work!

[FixedLPKs.zip](https://github.com/Rest-Dataware/RDW-Componente/files/2706089/FixedLPKs.zip)

**Comment by anderbelluno** [comment]
Hello Friend
I would like to invite you to post to Source Forge, which is the official repository for REST Dataware. We use GitHub only as a mirror and it does not always have the same version as in Source Forge.
Thanks for the help, this is important for our progress.

**Comment by zeljkoavramovic** [comment]
I didn't know that you also have a SF page. I couldn't find Github
page mentioning that. Anyway, thanks for all of your hard work.

Regards,
Avra


2018-12-23 20:04 GMT+01:00, anderbelluno <notifications@github.com>:
